name: Clone FSQ with Git Xet

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  clone:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Check git
        run: |
          git --version

      - name: Clone dataset with token
        env:
          HF_USERNAME: hellerremixing
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://$env:HF_USERNAME:$env:HF_TOKEN@huggingface.co/datasets/foursquare/fsq-os-places
